from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
OUTPUT = ROOT / "docs" / "cli-reference.md"
sys.path.insert(0, str(SRC))

from typer.main import get_command  # noqa: E402

from photosage.cli import app  # noqa: E402


def _text(value: object) -> str:
    if value is None:
        return "none"
    if isinstance(value, bool):
        return str(value).lower()
    if isinstance(value, (list, tuple)):
        return json.dumps(value)
    return str(value).replace("|", "\\|").replace("\n", " ")


def _parameter_names(parameter: Any) -> str:
    names = [*getattr(parameter, "opts", []), *getattr(parameter, "secondary_opts", [])]
    return ", ".join(f"`{name}`" for name in names) or f"`{parameter.name}`"


def _render_command(command: Any, path: list[str]) -> list[str]:
    invocation = "photosage " + " ".join(path)
    lines = [f"## `{invocation}`", "", command.help or "No description provided.", ""]
    is_group = hasattr(command, "commands")
    if is_group:
        lines.extend(["### Subcommands", "", "| Command | Purpose |", "| --- | --- |"])
        for name, child in command.commands.items():
            lines.append(f"| `{invocation} {name}` | {_text(child.help or '')} |")
        lines.append("")
    if command.params:
        lines.extend(["### Options", "", "| Option | Required | Default | Description |", "| --- | --- | --- | --- |"])
        for parameter in command.params:
            lines.append(
                f"| {_parameter_names(parameter)} | {'yes' if parameter.required else 'no'} | "
                f"`{_text(parameter.default)}` | {_text(getattr(parameter, 'help', '') or '')} |"
            )
        lines.append("")
    lines.extend(["```powershell", f"{invocation} --help", "```", ""])
    if is_group:
        for name, child in command.commands.items():
            lines.extend(_render_command(child, [*path, name]))
    return lines


def render_reference() -> str:
    root = get_command(app)
    lines = [
        "# CLI Reference",
        "",
        "> Generated by `python scripts/generate_cli_reference.py`. Do not edit command tables manually.",
        "",
        "This reference is generated from the Typer command tree, so command names, options, defaults, and help text match the executable.",
        "",
        "## Safety conventions",
        "",
        "- Commands that change filenames require an explicit apply flag.",
        "- Prefer `preview`, then `review`, then `rename --manifest ... --apply`.",
        "- `--local-only` blocks Anthropic, Gemini, Kimi, and OpenAI.",
        "- `--output-json` files may contain local paths and must be treated as private.",
        "- Use `--config` when the working directory does not contain `config/settings.yaml`.",
        "",
        "## Top-level commands",
        "",
        "| Command | Purpose |",
        "| --- | --- |",
    ]
    for name, command in root.commands.items():
        lines.append(f"| `photosage {name}` | {_text(command.help or '')} |")
    lines.append("")
    for name, command in root.commands.items():
        lines.extend(_render_command(command, [name]))
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render_reference()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print("ERROR: docs/cli-reference.md is stale. Run: python scripts/generate_cli_reference.py")
            return 1
        print("CLI reference is current.")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Updated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
